package Operacion.Egreso;

public enum TipoDePago {
    VISA,
    MASTERCARD,
    AMERCICANEXPRESS,
    DINERSCLUBINTERNATIONAL,
    TARJETANARANJA,
    TARJETANATIVA,
    TARJETASHOPPING,
    TARJETACENCOSUD,
    TARJETACMRMASTERCARD,
    ARGENCARD,
    CORDIAL,
    CORDOBESA,
    CABAL,
    VISADEBITO,
    MASTERCARDDEBITO,
    MAESTRO,
    CABALDEBITO,
    PAGOFACIL,
    RAPIPAGO,
    PROVINCIAPAGOS,
    CARGAVIRTUAL,
    COBROEXPRESS,
    REDLINK,
    DINEROENCUENTA
}
